### ISSUE TITLE
Dropdown menu renders wrongly on Ubuntu

### ISSUE THREAD

**Issue by Osoraa** [dracula/qbittorrent#10]
## Qbit-torrent on Ubuntu 22.04 jammy-jellyfish

Dropdown menus appear wrong in that the current selected option (like in the screenshot below) takes up too much space and drives the other options way down or up as the case may be.

![dracula_theme_dropdown](https://user-images.githubusercontent.com/51049054/190835421-44a53866-4716-4f27-84a4-a8cf43294ad7.png)

Here is another screenshot below of the same exact dropdown menu working fine in the normal/light theme.

![light_theme_dropdown](https://user-images.githubusercontent.com/51049054/190835320-f149fee8-f0ac-401d-b5c1-c32f6064c68a.png)

This occurs with all the dropdown menus in the Qbit application.

**Comment by MahdiMirzade** [comment]
This issue is now fixed by the latest theme update and re-writing the stylesheet.
Download it by [clicking here](https://github.com/dracula/qbittorrent/raw/master/dracula.qbtheme).

![image](https://user-images.githubusercontent.com/63877463/204336627-f79e576b-8f37-430e-aad1-c38204fed6db.png)

Reopen the issue if necessary.
