### ISSUE TITLE
The percentage of the progress bar is covered by the progress bar

### ISSUE THREAD

**Issue by asdffp** [dracula/qbittorrent#4]
The percentage of the progress bar is covered by the progress bar.Percentage will only be shown if progress is complete or if progress is low.As shown below
![image](https://user-images.githubusercontent.com/6636837/161417098-864d1dab-8ac2-4b32-a821-11b6986051ef.png)

**Comment by MahdiMirzade** [comment]
Hello, Based on the screenshot I'm assuming is this an issue on `.qbtheme` theme.
This doesn't seem to happen to me, even when it's downloading the progress-bar doesn't seem to override the progress-text.

Is your app up-to-date?
What is your OS and qbittorrent version?
Do you also have the newest theme file? because it seems like yours progress bar color is a little different from this theme.

![image](https://user-images.githubusercontent.com/63877463/161418800-4b813b58-030b-4da3-919f-e73a061d9687.png)
![image](https://user-images.githubusercontent.com/63877463/161418565-8d68eef4-66ef-4dec-aefa-c7654aae50f6.png)

**Comment by MahdiMirzade** [comment]
This issue is now fixed by the latest theme update and re-writing the stylesheet.
Download it by [clicking here](https://github.com/dracula/qbittorrent/raw/master/dracula.qbtheme).

Reopen the issue if necessary.
