### ISSUE TITLE
Change language not work

### ISSUE THREAD

**Issue by frostnotfall** [dracula/qbittorrent#9]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by frostnotfall** [comment]
![image](https://user-images.githubusercontent.com/38377709/183534576-39686c4a-1b0d-4f93-891b-6facd6b93935.png)

**Comment by MahdiMirzade** [comment]
I don't think this can be related to webui theme, I tried changing my language on my own qbittorrent-nox and it worked.
Try updating to the latest version.

**Comment by MahdiMirzade** [comment]
This is not an issue caused by this theme, you can see the screenshot down below:

![image](https://user-images.githubusercontent.com/63877463/204336084-d3ffb92f-3dfb-4cd8-b3dc-bb32b1486d69.png)

Update your operating system, with the latest version of qBittorrent, shouldn't be a problem.

Reopen the issue if necessary.
